/*
 * SuperMQ Combined Service
 *
 * This is the SuperMQ Combined Service based on the OpenAPI 3.0 specification.  It is the HTTP API for managing SuperMQ. You can now help us improve the API whether it's by making changes to the definition itself or to the code. Some useful links: - [The SuperMQ repository](https://github.com/absmach/supermq) 
 *
 * The version of the OpenAPI document: 0.15.1
 * Contact: info@abstractmachines.fr
 * Generated by: https://openapi-generator.tech
 */




#[derive(Clone, Debug, PartialEq, Default, Serialize, Deserialize)]
pub struct Cert {
    /// Corresponding SuperMQ Client ID.
    #[serde(rename = "client_id", skip_serializing_if = "Option::is_none")]
    pub client_id: Option<uuid::Uuid>,
    /// Client Certificate.
    #[serde(rename = "client_cert", skip_serializing_if = "Option::is_none")]
    pub client_cert: Option<String>,
    /// Key for the client_cert.
    #[serde(rename = "client_key", skip_serializing_if = "Option::is_none")]
    pub client_key: Option<String>,
    /// CA Certificate that is used to issue client certs, usually intermediate.
    #[serde(rename = "issuing_ca", skip_serializing_if = "Option::is_none")]
    pub issuing_ca: Option<String>,
    /// Certificate serial
    #[serde(rename = "serial", skip_serializing_if = "Option::is_none")]
    pub serial: Option<String>,
    /// Certificate expiry date
    #[serde(rename = "expire", skip_serializing_if = "Option::is_none")]
    pub expire: Option<String>,
}

#[derive(Clone, Debug, PartialEq, Default, Serialize, Deserialize)]
pub struct CertsPage {
    #[serde(rename = "certs", skip_serializing_if = "Option::is_none")]
    pub certs: Option<Vec<crate::models::Cert>>,
    /// Total number of items.
    #[serde(rename = "total", skip_serializing_if = "Option::is_none")]
    pub total: Option<i32>,
    /// Number of items to skip during retrieval.
    #[serde(rename = "offset", skip_serializing_if = "Option::is_none")]
    pub offset: Option<i32>,
    /// Maximum number of items to return in one page.
    #[serde(rename = "limit", skip_serializing_if = "Option::is_none")]
    pub limit: Option<i32>,
}

#[derive(Clone, Debug, PartialEq, Default, Serialize, Deserialize)]
pub struct CreateCertRequest {
    #[serde(rename = "client_id")]
    pub client_id: uuid::Uuid,
    #[serde(rename = "ttl")]
    pub ttl: String,
}

#[derive(Clone, Debug, PartialEq, Default, Serialize, Deserialize)]
pub struct Revoke {
    /// Certificate revocation time
    #[serde(rename = "revocation_time", skip_serializing_if = "Option::is_none")]
    pub revocation_time: Option<String>,
}

impl Revoke {
    pub fn new() -> Revoke {
        Revoke {
            revocation_time: None,
        }
    }
}


impl CreateCertRequest {
    pub fn new(client_id: uuid::Uuid, ttl: String) -> CreateCertRequest {
        CreateCertRequest {
            client_id,
            ttl,
        }
    }
}

impl CertsPage {
    pub fn new() -> CertsPage {
        CertsPage {
            certs: None,
            total: None,
            offset: None,
            limit: None,
        }
    }
}

impl Cert {
    pub fn new() -> Cert {
        Cert {
            client_id: None,
            client_cert: None,
            client_key: None,
            issuing_ca: None,
            serial: None,
            expire: None,
        }
    }
}


