/*
 * SuperMQ Combined Service
 *
 * This is the SuperMQ Combined Service based on the OpenAPI 3.0 specification.  It is the HTTP API for managing SuperMQ. You can now help us improve the API whether it's by making changes to the definition itself or to the code. Some useful links: - [The SuperMQ repository](https://github.com/absmach/supermq) 
 *
 * The version of the OpenAPI document: 0.15.1
 * Contact: info@abstractmachines.fr
 * Generated by: https://openapi-generator.tech
 */






 #[derive(Clone, Debug, PartialEq, Default, Serialize, Deserialize)]
pub struct Invitation {
    /// User unique identifier.
    #[serde(rename = "invited_by", skip_serializing_if = "Option::is_none")]
    pub invited_by: Option<uuid::Uuid>,
    /// User unique identifier.
    #[serde(rename = "user_id", skip_serializing_if = "Option::is_none")]
    pub user_id: Option<uuid::Uuid>,
    /// Domain unique identifier.
    #[serde(rename = "domain_id", skip_serializing_if = "Option::is_none")]
    pub domain_id: Option<uuid::Uuid>,
    /// Relation between user and domain.
    #[serde(rename = "relation", skip_serializing_if = "Option::is_none")]
    pub relation: Option<Relation>,
    /// Time when the group was created.
    #[serde(rename = "created_at", skip_serializing_if = "Option::is_none")]
    pub created_at: Option<String>,
    /// Time when the group was created.
    #[serde(rename = "updated_at", skip_serializing_if = "Option::is_none")]
    pub updated_at: Option<String>,
    /// Time when the group was created.
    #[serde(rename = "confirmed_at", skip_serializing_if = "Option::is_none")]
    pub confirmed_at: Option<String>,
}

#[derive(Clone, Debug, PartialEq, Default, Serialize, Deserialize)]
pub struct InvitationPage {
    #[serde(rename = "invitations")]
    pub invitations: Vec<crate::models::Invitation>,
    /// Total number of items.
    #[serde(rename = "total")]
    pub total: i32,
    /// Number of items to skip during retrieval.
    #[serde(rename = "offset")]
    pub offset: i32,
    /// Maximum number of items to return in one page.
    #[serde(rename = "limit", skip_serializing_if = "Option::is_none")]
    pub limit: Option<i32>,
}

#[derive(Clone, Debug, PartialEq, Default, Serialize, Deserialize)]
pub struct SendInvitationReqObj {
    /// User unique identifier.
    #[serde(rename = "user_id")]
    pub user_id: uuid::Uuid,
    /// Domain unique identifier.
    #[serde(rename = "domain_id")]
    pub domain_id: uuid::Uuid,
    /// Relation between user and domain.
    #[serde(rename = "relation")]
    pub relation: Relation,
    /// Resend invitation.
    #[serde(rename = "resend", skip_serializing_if = "Option::is_none")]
    pub resend: Option<bool>,
}

#[derive(Clone, Debug, PartialEq, Default, Serialize, Deserialize)]
pub struct AcceptInvitationRequest {
    /// Domain unique identifier.
    #[serde(rename = "domain_id")]
    pub domain_id: uuid::Uuid,
}

#[derive(Clone, Copy, Debug, Eq, PartialEq, Ord, PartialOrd, Hash, Serialize, Deserialize)]
pub enum Relation {
    #[serde(rename = "administrator")]
    Administrator,
    #[serde(rename = "editor")]
    Editor,
    #[serde(rename = "contributor")]
    Contributor,
    #[serde(rename = "member")]
    Member,
    #[serde(rename = "guest")]
    Guest,
    #[serde(rename = "domain")]
    Domain,
    #[serde(rename = "parent_group")]
    ParentGroup,
    #[serde(rename = "role_group")]
    RoleGroup,
    #[serde(rename = "group")]
    Group,
    #[serde(rename = "platform")]
    Platform,
}

impl AcceptInvitationRequest {
    pub fn new(domain_id: uuid::Uuid) -> AcceptInvitationRequest {
        AcceptInvitationRequest {
            domain_id,
        }
    }
}

impl SendInvitationReqObj {
    pub fn new(user_id: uuid::Uuid, domain_id: uuid::Uuid, relation: Relation) -> SendInvitationReqObj {
        SendInvitationReqObj {
            user_id,
            domain_id,
            relation,
            resend: None,
        }
    }
}

impl InvitationPage {
    pub fn new(invitations: Vec<crate::models::Invitation>, total: i32, offset: i32) -> InvitationPage {
        InvitationPage {
            invitations,
            total,
            offset,
            limit: None,
        }
    }
}

impl Invitation {
    pub fn new() -> Invitation {
        Invitation {
            invited_by: None,
            user_id: None,
            domain_id: None,
            relation: None,
            created_at: None,
            updated_at: None,
            confirmed_at: None,
        }
    }
}

impl Default for Relation {
    fn default() -> Relation {
        Self::Administrator
    }
}

