/*
 * SuperMQ Combined Service
 *
 * This is the SuperMQ Combined Service based on the OpenAPI 3.0 specification.  It is the HTTP API for managing SuperMQ. You can now help us improve the API whether it's by making changes to the definition itself or to the code. Some useful links: - [The SuperMQ repository](https://github.com/absmach/supermq) 
 *
 * The version of the OpenAPI document: 0.15.1
 * Contact: info@abstractmachines.fr
 * Generated by: https://openapi-generator.tech
 */





#[derive(Clone, Debug, PartialEq, Default, Serialize, Deserialize)]
 pub struct AvailableActionsObj {
     /// List of all available actions.
     #[serde(rename = "available_actions", skip_serializing_if = "Option::is_none")]
     pub available_actions: Option<Vec<String>>,
 }

 #[derive(Clone, Debug, PartialEq, Default, Serialize, Deserialize)]
 pub struct ConfigChannelsInner {
    /// Channel unique identifier.
    #[serde(rename = "id", skip_serializing_if = "Option::is_none")]
    pub id: Option<uuid::Uuid>,
    /// Name of the Channel.
    #[serde(rename = "name", skip_serializing_if = "Option::is_none")]
    pub name: Option<String>,
    /// Custom metadata related to the Channel.
    #[serde(rename = "metadata", skip_serializing_if = "Option::is_none")]
    pub metadata: Option<serde_json::Value>,
}

#[derive(Clone, Debug, PartialEq, Default, Serialize, Deserialize)]
pub struct CreateRoleObj {
    /// Role's name.
    #[serde(rename = "role_name", skip_serializing_if = "Option::is_none")]
    pub role_name: Option<String>,
    /// List of optional actions.
    #[serde(rename = "optional_actions", skip_serializing_if = "Option::is_none")]
    pub optional_actions: Option<Vec<String>>,
    /// List of optional members.
    #[serde(rename = "optional_members", skip_serializing_if = "Option::is_none")]
    pub optional_members: Option<Vec<String>>,
}

#[derive(Clone, Debug, PartialEq, Default, Serialize, Deserialize)]
pub struct Error {
    /// Error message
    #[serde(rename = "error", skip_serializing_if = "Option::is_none")]
    pub error: Option<String>,
}

#[derive(Clone, Debug, PartialEq, Default, Serialize, Deserialize)]
pub struct HealthInfo {
    /// Service status.
    #[serde(rename = "status", skip_serializing_if = "Option::is_none")]
    pub status: Option<Status>,
    /// Service version.
    #[serde(rename = "version", skip_serializing_if = "Option::is_none")]
    pub version: Option<String>,
    /// Service commit hash.
    #[serde(rename = "commit", skip_serializing_if = "Option::is_none")]
    pub commit: Option<String>,
    /// Service description.
    #[serde(rename = "description", skip_serializing_if = "Option::is_none")]
    pub description: Option<String>,
    /// Service build time.
    #[serde(rename = "build_time", skip_serializing_if = "Option::is_none")]
    pub build_time: Option<String>,
    /// Service instance ID.
    #[serde(rename = "instance_id", skip_serializing_if = "Option::is_none")]
    pub instance_id: Option<String>,
}

#[derive(Clone, Debug, PartialEq, Default, Serialize, Deserialize)]
pub struct HealthRes {
    /// Service status.
    #[serde(rename = "status", skip_serializing_if = "Option::is_none")]
    pub status: Option<Status>,
    /// Service version.
    #[serde(rename = "version", skip_serializing_if = "Option::is_none")]
    pub version: Option<String>,
    /// Service commit hash.
    #[serde(rename = "commit", skip_serializing_if = "Option::is_none")]
    pub commit: Option<String>,
    /// Service description.
    #[serde(rename = "description", skip_serializing_if = "Option::is_none")]
    pub description: Option<String>,
    /// Service build time.
    #[serde(rename = "build_time", skip_serializing_if = "Option::is_none")]
    pub build_time: Option<String>,
}

#[derive(Clone, Copy, Debug, Eq, PartialEq, Ord, PartialOrd, Hash, Serialize, Deserialize)]
pub enum Status {
    #[serde(rename = "pass")]
    Pass,
}

#[derive(Clone, Debug, PartialEq, Default, Serialize, Deserialize)]
pub struct Key {
    /// API key unique identifier
    #[serde(rename = "id", skip_serializing_if = "Option::is_none")]
    pub id: Option<uuid::Uuid>,
    /// In ID of the entity that issued the token.
    #[serde(rename = "issuer_id", skip_serializing_if = "Option::is_none")]
    pub issuer_id: Option<uuid::Uuid>,
    /// API key type. Keys of different type are processed differently.
    #[serde(rename = "type", skip_serializing_if = "Option::is_none")]
    pub r#type: Option<i32>,
    /// User's email or service identifier of API key subject.
    #[serde(rename = "subject", skip_serializing_if = "Option::is_none")]
    pub subject: Option<String>,
    /// Time when the key is generated.
    #[serde(rename = "issued_at", skip_serializing_if = "Option::is_none")]
    pub issued_at: Option<String>,
    /// Time when the Key expires. If this field is missing, that means that Key is valid indefinitely.
    #[serde(rename = "expires_at", skip_serializing_if = "Option::is_none")]
    pub expires_at: Option<String>,
}

#[derive(Clone, Debug, PartialEq, Default, Serialize, Deserialize)]
pub struct IssueKeyRequest {
    /// API key type. Keys of different type are processed differently.
    #[serde(rename = "type", skip_serializing_if = "Option::is_none")]
    pub r#type: Option<i32>,
    /// Number of seconds issued token is valid for.
    #[serde(rename = "duration", skip_serializing_if = "Option::is_none")]
    pub duration: Option<f32>,
}

#[derive(Clone, Debug, PartialEq, Default, Serialize, Deserialize)]
pub struct Members {
    /// User unique identifier.
    #[serde(rename = "id", skip_serializing_if = "Option::is_none")]
    pub id: Option<uuid::Uuid>,
    /// User's first name.
    #[serde(rename = "first_name", skip_serializing_if = "Option::is_none")]
    pub first_name: Option<String>,
    /// User's last name.
    #[serde(rename = "last_name", skip_serializing_if = "Option::is_none")]
    pub last_name: Option<String>,
    /// User's email address.
    #[serde(rename = "email", skip_serializing_if = "Option::is_none")]
    pub email: Option<String>,
    /// User tags.
    #[serde(rename = "tags", skip_serializing_if = "Option::is_none")]
    pub tags: Option<Vec<String>>,
    #[serde(rename = "credentials", skip_serializing_if = "Option::is_none")]
    pub credentials: Option<Box<crate::models::MembersCredentials>>,
    /// Arbitrary, object-encoded user's data.
    #[serde(rename = "metadata", skip_serializing_if = "Option::is_none")]
    pub metadata: Option<serde_json::Value>,
    /// User Status
    #[serde(rename = "status", skip_serializing_if = "Option::is_none")]
    pub status: Option<String>,
    /// Time when the group was created.
    #[serde(rename = "created_at", skip_serializing_if = "Option::is_none")]
    pub created_at: Option<String>,
    /// Time when the group was created.
    #[serde(rename = "updated_at", skip_serializing_if = "Option::is_none")]
    pub updated_at: Option<String>,
}

#[derive(Clone, Debug, PartialEq, Default, Serialize, Deserialize)]
pub struct MembersCredentials {
    /// User's username.
    #[serde(rename = "username", skip_serializing_if = "Option::is_none")]
    pub username: Option<String>,
    /// User secret password.
    #[serde(rename = "secret", skip_serializing_if = "Option::is_none")]
    pub secret: Option<String>,
}

#[derive(Clone, Debug, PartialEq, Default, Serialize, Deserialize)]
pub struct MembersPage {
    #[serde(rename = "members")]
    pub members: Vec<crate::models::Members>,
    /// Total number of items.
    #[serde(rename = "total")]
    pub total: i32,
    /// Number of items to skip during retrieval.
    #[serde(rename = "offset", skip_serializing_if = "Option::is_none")]
    pub offset: Option<i32>,
    /// Maximum number of items to return in one page.
    #[serde(rename = "limit", skip_serializing_if = "Option::is_none")]
    pub limit: Option<i32>,
}

#[derive(Clone, Debug, PartialEq, Default, Serialize, Deserialize)]
pub struct NewRole {
    /// Role unique identifier.
    #[serde(rename = "role_id", skip_serializing_if = "Option::is_none")]
    pub role_id: Option<uuid::Uuid>,
    /// Role's name.
    #[serde(rename = "role_name", skip_serializing_if = "Option::is_none")]
    pub role_name: Option<String>,
    /// Entity unique identifier.
    #[serde(rename = "entity_id", skip_serializing_if = "Option::is_none")]
    pub entity_id: Option<uuid::Uuid>,
    /// Role creator unique identifier.
    #[serde(rename = "created_by", skip_serializing_if = "Option::is_none")]
    pub created_by: Option<uuid::Uuid>,
    /// Time when the channel was created.
    #[serde(rename = "created_at", skip_serializing_if = "Option::is_none")]
    pub created_at: Option<String>,
    /// Role updater unique identifier.
    #[serde(rename = "updated_by", skip_serializing_if = "Option::is_none")]
    pub updated_by: Option<uuid::Uuid>,
    /// Time when the channel was created.
    #[serde(rename = "updated_at", skip_serializing_if = "Option::is_none")]
    pub updated_at: Option<String>,
}

#[derive(Clone, Debug, PartialEq, Default, Serialize, Deserialize)]
pub struct Page {
    #[serde(rename = "subscriptions", skip_serializing_if = "Option::is_none")]
    pub subscriptions: Option<Vec<crate::models::Subscription>>,
    /// Total number of items.
    #[serde(rename = "total", skip_serializing_if = "Option::is_none")]
    pub total: Option<i32>,
    /// Number of items to skip during retrieval.
    #[serde(rename = "offset", skip_serializing_if = "Option::is_none")]
    pub offset: Option<i32>,
    /// Maximum number of items to return in one page.
    #[serde(rename = "limit", skip_serializing_if = "Option::is_none")]
    pub limit: Option<i32>,
}

#[derive(Clone, Debug, PartialEq, Default, Serialize, Deserialize)]
pub struct ParentGroupReqObj {
    /// Parent group unique identifier.
    #[serde(rename = "parent_group_id")]
    pub parent_group_id: uuid::Uuid,
}

#[derive(Clone, Debug, PartialEq, Default, Serialize, Deserialize)]
 pub struct Role {
     /// Role unique identifier.
     #[serde(rename = "role_id", skip_serializing_if = "Option::is_none")]
     pub role_id: Option<uuid::Uuid>,
     /// Role's name.
     #[serde(rename = "role_name", skip_serializing_if = "Option::is_none")]
     pub role_name: Option<String>,
     /// Entity unique identifier.
     #[serde(rename = "entity_id", skip_serializing_if = "Option::is_none")]
     pub entity_id: Option<uuid::Uuid>,
     /// Role creator unique identifier.
     #[serde(rename = "created_by", skip_serializing_if = "Option::is_none")]
     pub created_by: Option<uuid::Uuid>,
     /// Time when the channel was created.
     #[serde(rename = "created_at", skip_serializing_if = "Option::is_none")]
     pub created_at: Option<String>,
     /// Role updater unique identifier.
     #[serde(rename = "updated_by", skip_serializing_if = "Option::is_none")]
     pub updated_by: Option<uuid::Uuid>,
     /// Time when the channel was created.
     #[serde(rename = "updated_at", skip_serializing_if = "Option::is_none")]
     pub updated_at: Option<String>,
 }
 
 #[derive(Clone, Debug, PartialEq, Default, Serialize, Deserialize)]
 pub struct RoleMembersObj {
     /// List of members to be added to a role.
     #[serde(rename = "members", skip_serializing_if = "Option::is_none")]
     pub members: Option<Vec<String>>,
 }
 
 #[derive(Clone, Debug, PartialEq, Default, Serialize, Deserialize)]
 pub struct RoleActionsObj {
     /// List of actions to be added to a role.
     #[serde(rename = "actions", skip_serializing_if = "Option::is_none")]
     pub actions: Option<Vec<String>>,
 }
 
 #[derive(Clone, Debug, PartialEq, Default, Serialize, Deserialize)]
 pub struct RolesPage {
     /// List of roles.
     #[serde(rename = "roles", skip_serializing_if = "Option::is_none")]
     pub roles: Option<Vec<crate::models::Role>>,
     /// Total number of roles.
     #[serde(rename = "total", skip_serializing_if = "Option::is_none")]
     pub total: Option<i32>,
     /// Number of items to skip during retrieval.
     #[serde(rename = "offset", skip_serializing_if = "Option::is_none")]
     pub offset: Option<i32>,
     /// Maximum number of items to return in one page.
     #[serde(rename = "limit", skip_serializing_if = "Option::is_none")]
     pub limit: Option<i32>,
 }

 #[derive(Clone, Debug, PartialEq, Default, Serialize, Deserialize)]
 pub struct Serial {
    /// Certificate serial
    #[serde(rename = "serial", skip_serializing_if = "Option::is_none")]
    pub serial: Option<String>,
}

#[derive(Clone, Debug, PartialEq, Default, Serialize, Deserialize)]
pub struct SerialsPage {
    /// Certificate serials IDs.
    #[serde(rename = "serials", skip_serializing_if = "Option::is_none")]
    pub serials: Option<Vec<String>>,
    /// Total number of items.
    #[serde(rename = "total", skip_serializing_if = "Option::is_none")]
    pub total: Option<i32>,
    /// Number of items to skip during retrieval.
    #[serde(rename = "offset", skip_serializing_if = "Option::is_none")]
    pub offset: Option<i32>,
    /// Maximum number of items to return in one page.
    #[serde(rename = "limit", skip_serializing_if = "Option::is_none")]
    pub limit: Option<i32>,
}

#[derive(Clone, Debug, PartialEq, Default, Serialize, Deserialize)]
pub struct SenMlRecord {
    /// Base Name
    #[serde(rename = "bn", skip_serializing_if = "Option::is_none")]
    pub bn: Option<String>,
    /// Base Time
    #[serde(rename = "bt", skip_serializing_if = "Option::is_none")]
    pub bt: Option<f64>,
    /// Base Unit
    #[serde(rename = "bu", skip_serializing_if = "Option::is_none")]
    pub bu: Option<f64>,
    /// Base Value
    #[serde(rename = "bv", skip_serializing_if = "Option::is_none")]
    pub bv: Option<f64>,
    /// Base Sum
    #[serde(rename = "bs", skip_serializing_if = "Option::is_none")]
    pub bs: Option<f64>,
    /// Version
    #[serde(rename = "bver", skip_serializing_if = "Option::is_none")]
    pub bver: Option<f64>,
    /// Name
    #[serde(rename = "n", skip_serializing_if = "Option::is_none")]
    pub n: Option<String>,
    /// Unit
    #[serde(rename = "u", skip_serializing_if = "Option::is_none")]
    pub u: Option<String>,
    /// Value
    #[serde(rename = "v", skip_serializing_if = "Option::is_none")]
    pub v: Option<f64>,
    /// String Value
    #[serde(rename = "vs", skip_serializing_if = "Option::is_none")]
    pub vs: Option<String>,
    /// Boolean Value
    #[serde(rename = "vb", skip_serializing_if = "Option::is_none")]
    pub vb: Option<bool>,
    /// Data Value
    #[serde(rename = "vd", skip_serializing_if = "Option::is_none")]
    pub vd: Option<String>,
    /// Value Sum
    #[serde(rename = "s", skip_serializing_if = "Option::is_none")]
    pub s: Option<f64>,
    /// Time
    #[serde(rename = "t", skip_serializing_if = "Option::is_none")]
    pub t: Option<f64>,
    /// Update Time
    #[serde(rename = "ut", skip_serializing_if = "Option::is_none")]
    pub ut: Option<f64>,
}

#[derive(Clone, Copy, Debug, Eq, PartialEq, Ord, PartialOrd, Hash, Serialize, Deserialize)]
pub enum State {
    #[serde(rename = "0")]
    Variant0,
    #[serde(rename = "1")]
    Variant1,

}

#[derive(Clone, Debug, PartialEq, Default, Serialize, Deserialize)]
pub struct StatesPage {
    #[serde(rename = "states")]
    pub states: Vec<crate::models::State2>,
    /// Total number of items.
    #[serde(rename = "total", skip_serializing_if = "Option::is_none")]
    pub total: Option<i32>,
    /// Number of items to skip during retrieval.
    #[serde(rename = "offset", skip_serializing_if = "Option::is_none")]
    pub offset: Option<i32>,
    /// Maximum number of items to return in one page.
    #[serde(rename = "limit", skip_serializing_if = "Option::is_none")]
    pub limit: Option<i32>,
}

#[derive(Clone, Debug, PartialEq, Default, Serialize, Deserialize)]
pub struct UpdateRoleObj {
    /// Role's name.
    #[serde(rename = "name", skip_serializing_if = "Option::is_none")]
    pub name: Option<String>,
}


impl UpdateRoleObj {
    pub fn new() -> UpdateRoleObj {
        UpdateRoleObj {
            name: None,
        }
    }
}

impl StatesPage {
    pub fn new(states: Vec<crate::models::State2>) -> StatesPage {
        StatesPage {
            states,
            total: None,
            offset: None,
            limit: None,
        }
    }
}

impl ToString for State {
    fn to_string(&self) -> String {
        match self {
            Self::Variant0 => String::from("0"),
            Self::Variant1 => String::from("1"),
        }
    }
}

impl Default for State {
    fn default() -> State {
        Self::Variant0
    }
}

impl SenMlRecord {
    pub fn new() -> SenMlRecord {
        SenMlRecord {
            bn: None,
            bt: None,
            bu: None,
            bv: None,
            bs: None,
            bver: None,
            n: None,
            u: None,
            v: None,
            vs: None,
            vb: None,
            vd: None,
            s: None,
            t: None,
            ut: None,
        }
    }
}

impl SerialsPage {
    pub fn new() -> SerialsPage {
        SerialsPage {
            serials: None,
            total: None,
            offset: None,
            limit: None,
        }
    }
}

impl Serial {
    pub fn new() -> Serial {
        Serial {
            serial: None,
        }
    }
}
 
 impl RolesPage {
     pub fn new() -> RolesPage {
         RolesPage {
             roles: None,
             total: None,
             offset: None,
             limit: None,
         }
     }
 }
 
 impl RoleActionsObj {
     pub fn new() -> RoleActionsObj {
         RoleActionsObj {
             actions: None,
         }
     }
 }
 
 impl RoleMembersObj {
     pub fn new() -> RoleMembersObj {
         RoleMembersObj {
             members: None,
         }
     }
 }
 
 impl Role {
     pub fn new() -> Role {
         Role {
             role_id: None,
             role_name: None,
             entity_id: None,
             created_by: None,
             created_at: None,
             updated_by: None,
             updated_at: None,
         }
     }
 }
 
 impl ParentGroupReqObj {
    pub fn new(parent_group_id: uuid::Uuid) -> ParentGroupReqObj {
        ParentGroupReqObj {
            parent_group_id,
        }
    }
}

impl Page {
    pub fn new() -> Page {
        Page {
            subscriptions: None,
            total: None,
            offset: None,
            limit: None,
        }
    }
}

impl NewRole {
    pub fn new() -> NewRole {
        NewRole {
            role_id: None,
            role_name: None,
            entity_id: None,
            created_by: None,
            created_at: None,
            updated_by: None,
            updated_at: None,
        }
    }
}

impl MembersPage {
    pub fn new(members: Vec<crate::models::Members>, total: i32) -> MembersPage {
        MembersPage {
            members,
            total,
            offset: None,
            limit: None,
        }
    }
}

impl MembersCredentials {
    pub fn new() -> MembersCredentials {
        MembersCredentials {
            username: None,
            secret: None,
        }
    }
}

impl Members {
    pub fn new() -> Members {
        Members {
            id: None,
            first_name: None,
            last_name: None,
            email: None,
            tags: None,
            credentials: None,
            metadata: None,
            status: None,
            created_at: None,
            updated_at: None,
        }
    }
}

impl IssueKeyRequest {
    pub fn new() -> IssueKeyRequest {
        IssueKeyRequest {
            r#type: None,
            duration: None,
        }
    }
}

impl Key {
    pub fn new() -> Key {
        Key {
            id: None,
            issuer_id: None,
            r#type: None,
            subject: None,
            issued_at: None,
            expires_at: None,
        }
    }
}

impl Default for Status {
    fn default() -> Status {
        Self::Pass
    }
}

impl HealthRes {
    pub fn new() -> HealthRes {
        HealthRes {
            status: None,
            version: None,
            commit: None,
            description: None,
            build_time: None,
        }
    }
}

impl HealthInfo {
    pub fn new() -> HealthInfo {
        HealthInfo {
            status: None,
            version: None,
            commit: None,
            description: None,
            build_time: None,
            instance_id: None,
        }
    }
}

impl Error {
    pub fn new() -> Error {
        Error {
            error: None,
        }
    }
}

impl CreateRoleObj {
    pub fn new() -> CreateRoleObj {
        CreateRoleObj {
            role_name: None,
            optional_actions: None,
            optional_members: None,
        }
    }
}

impl ConfigChannelsInner {
    pub fn new() -> ConfigChannelsInner {
        ConfigChannelsInner {
            id: None,
            name: None,
            metadata: None,
        }
    }
}

 impl AvailableActionsObj {
     pub fn new() -> AvailableActionsObj {
         AvailableActionsObj {
             available_actions: None,
         }
     }
 }