/*
 * SuperMQ Combined Service
 *
 * This is the SuperMQ Combined Service based on the OpenAPI 3.0 specification.  It is the HTTP API for managing SuperMQ. You can now help us improve the API whether it's by making changes to the definition itself or to the code. Some useful links: - [The SuperMQ repository](https://github.com/absmach/supermq) 
 *
 * The version of the OpenAPI document: 0.15.1
 * Contact: info@abstractmachines.fr
 * Generated by: https://openapi-generator.tech
 */




#[derive(Clone, Debug, PartialEq, Default, Serialize, Deserialize)]
pub struct TwinReqObj {
    /// Free-form twin name.
    #[serde(rename = "name", skip_serializing_if = "Option::is_none")]
    pub name: Option<String>,
    /// Arbitrary, object-encoded twin's data.
    #[serde(rename = "metadata", skip_serializing_if = "Option::is_none")]
    pub metadata: Option<serde_json::Value>,
    #[serde(rename = "definition", skip_serializing_if = "Option::is_none")]
    pub definition: Option<Box<crate::models::Definition>>,
}

#[derive(Clone, Debug, PartialEq, Default, Serialize, Deserialize)]
pub struct State2 {
    /// ID of twin state belongs to.
    #[serde(rename = "twin_id", skip_serializing_if = "Option::is_none")]
    pub twin_id: Option<uuid::Uuid>,
    /// State position in a time row of states.
    #[serde(rename = "id", skip_serializing_if = "Option::is_none")]
    pub id: Option<f32>,
    /// State creation date.
    #[serde(rename = "created", skip_serializing_if = "Option::is_none")]
    pub created: Option<String>,
    /// Object-encoded states's payload.
    #[serde(rename = "payload", skip_serializing_if = "Option::is_none")]
    pub payload: Option<serde_json::Value>,
}

#[derive(Clone, Debug, PartialEq, Default, Serialize, Deserialize)]
pub struct TwinResObj {
    /// Email address of SuperMQ user that owns twin.
    #[serde(rename = "owner", skip_serializing_if = "Option::is_none")]
    pub owner: Option<String>,
    /// Unique twin identifier generated by the service.
    #[serde(rename = "id", skip_serializing_if = "Option::is_none")]
    pub id: Option<uuid::Uuid>,
    /// Free-form twin name.
    #[serde(rename = "name", skip_serializing_if = "Option::is_none")]
    pub name: Option<String>,
    /// Oridnal revision number of twin.
    #[serde(rename = "revision", skip_serializing_if = "Option::is_none")]
    pub revision: Option<f32>,
    /// Twin creation date and time.
    #[serde(rename = "created", skip_serializing_if = "Option::is_none")]
    pub created: Option<String>,
    /// Twin update date and time.
    #[serde(rename = "updated", skip_serializing_if = "Option::is_none")]
    pub updated: Option<String>,
    #[serde(rename = "definitions", skip_serializing_if = "Option::is_none")]
    pub definitions: Option<Vec<crate::models::Definition>>,
    /// Arbitrary, object-encoded twin's data.
    #[serde(rename = "metadata", skip_serializing_if = "Option::is_none")]
    pub metadata: Option<serde_json::Value>,
}

#[derive(Clone, Debug, PartialEq, Default, Serialize, Deserialize)]
pub struct TwinsPage {
    #[serde(rename = "twins")]
    pub twins: Vec<crate::models::TwinResObj>,
    /// Total number of items.
    #[serde(rename = "total", skip_serializing_if = "Option::is_none")]
    pub total: Option<i32>,
    /// Number of items to skip during retrieval.
    #[serde(rename = "offset", skip_serializing_if = "Option::is_none")]
    pub offset: Option<i32>,
    /// Maximum number of items to return in one page.
    #[serde(rename = "limit", skip_serializing_if = "Option::is_none")]
    pub limit: Option<i32>,
}

#[derive(Clone, Debug, PartialEq, Default, Serialize, Deserialize)]
pub struct Attribute {
    /// Name of the attribute.
    #[serde(rename = "name", skip_serializing_if = "Option::is_none")]
    pub name: Option<String>,
    /// SuperMQ channel used by attribute.
    #[serde(rename = "channel", skip_serializing_if = "Option::is_none")]
    pub channel: Option<String>,
    /// Subtopic used by attribute.
    #[serde(rename = "subtopic", skip_serializing_if = "Option::is_none")]
    pub subtopic: Option<String>,
    /// Trigger state creation based on the attribute.
    #[serde(rename = "persist_state", skip_serializing_if = "Option::is_none")]
    pub persist_state: Option<bool>,
}

#[derive(Clone, Debug, PartialEq, Default, Serialize, Deserialize)]
pub struct Definition {
    /// Minimal time delay before new state creation.
    #[serde(rename = "delta", skip_serializing_if = "Option::is_none")]
    pub delta: Option<f32>,
    #[serde(rename = "attributes", skip_serializing_if = "Option::is_none")]
    pub attributes: Option<Vec<crate::models::Attribute>>,
}

impl Definition {
    pub fn new() -> Definition {
        Definition {
            delta: None,
            attributes: None,
        }
    }
}

impl Attribute {
    pub fn new() -> Attribute {
        Attribute {
            name: None,
            channel: None,
            subtopic: None,
            persist_state: None,
        }
    }
}

impl TwinsPage {
    pub fn new(twins: Vec<crate::models::TwinResObj>) -> TwinsPage {
        TwinsPage {
            twins,
            total: None,
            offset: None,
            limit: None,
        }
    }
}

impl TwinResObj {
    pub fn new() -> TwinResObj {
        TwinResObj {
            owner: None,
            id: None,
            name: None,
            revision: None,
            created: None,
            updated: None,
            definitions: None,
            metadata: None,
        }
    }
}

impl TwinReqObj {
    pub fn new() -> TwinReqObj {
        TwinReqObj {
            name: None,
            metadata: None,
            definition: None,
        }
    }
}

impl State2 {
    pub fn new() -> State2 {
        State2 {
            twin_id: None,
            id: None,
            created: None,
            payload: None,
        }
    }
}
